version: '3.3'

services:
  database:
    container_name: wordpress_mysql
    image: mysql:5.7
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    container_name: wordpress_app
    depends_on:
      - database
    image: wp-cli:latest
    build:
      dockerfile: Dockerfile
      context: ./dockerfile
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress 
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:
